FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm config set registry https://registry.npmjs.org/ && npm install
RUN apk add --no-cache postgresql-client

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]


# docker-compose -f docker-compose.dev.yml up --build

#----------Prisma Running Migrations-----------------

# In dev:

# docker-compose exec api npx prisma migrate dev --name init

#---------Docker prisma generate--------------------
# docker-compose exec api npx prisma generate

#---------Docker prisma migrate--------------------
# docker-compose exec api npx prisma migrate dev --name add_user_model
#npm run dev:migrate -- --name add_refresh_tokens

