
FROM grafana/grafana:latest

# Switch to root to perform cleanup
USER root


RUN rm -rf /usr/share/grafana/public/explore \
           /usr/share/grafana/public/img \
           /usr/share/grafana/public/vendor || true


USER 472

EXPOSE 3000

